# Generated by Django 5.0.7 on 2024-08-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_product_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_for_login', to='projectapp.login')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_for_product', to='projectapp.product')),
            ],
        ),
    ]
