# Generated by Django 5.0.7 on 2024-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
