# Generated by Django 5.0.7 on 2024-09-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
