# Generated by Django 5.0.7 on 2024-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_remove_product_category_name_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
