# Generated by Django 5.0.7 on 2024-09-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_shop_address_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectapp.login'),
        ),
        migrations.AddField(
            model_name='shop',
            name='role',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
