# Generated by Django 5.0.7 on 2024-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_shop_login_id_shop_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login'),
        ),
    ]
