# Generated by Django 5.0.7 on 2024-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_shop_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='login_id',
            new_name='Login_id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
