# Generated by Django 5.0.7 on 2024-09-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_rename_login_id_shop_login_id_alter_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login'),
        ),
    ]
