# Generated by Django 5.0.7 on 2024-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_rename_login_id_shop_login_id_alter_shop_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('cart_status', models.CharField(max_length=30)),
            ],
        ),
    ]
